spring:
  cloud:
    gateway:
      routes:
      - id: service-producer
        uri: lb://service-producer
        predicates:
          - Path=/gateway/api/producer/**
        filters:
          - StripPrefix=3
      - id: service-client
        uri: lb://service-client
        predicates:
          - Path=/gateway/api/client/**
        filters:
          - StripPrefix=3